# Generated by Django 2.0 on 2018-04-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=20, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dral_text.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=20)),
                ('sentence_index', models.IntegerField()),
                ('context', models.CharField(blank=True, max_length=30)),
                ('lemma_group', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dral_text.Language')),
                ('lemma', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='dral_text.Lemma')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=500)),
                ('index', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dral_text.Language')),
            ],
        ),
    ]
