# Generated by Django 2.0 on 2018-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0002_auto_20180420_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='cell',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
