# Generated by Django 2.0 on 2018-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0003_occurence_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
