# Generated by Django 2.0 on 2018-04-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0004_auto_20180421_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='paraphrase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurence',
            name='replace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurence',
            name='zero',
            field=models.BooleanField(default=False),
        ),
    ]
