# Generated by Django 2.0 on 2018-04-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0005_auto_20180421_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='cell_style',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
