# Generated by Django 2.0 on 2018-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0006_occurence_cell_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='cell_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='occurence',
            name='cell_line',
            field=models.IntegerField(default=0),
        ),
    ]
