# Generated by Django 2.0 on 2018-04-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0007_auto_20180422_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
    ]
