# Generated by Django 2.0 on 2018-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0008_sheetstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='chapter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sentence',
            name='chapter',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
