# Generated by Django 2.0 on 2018-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0009_auto_20180422_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='freq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sheetstyle',
            name='chapter',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
