# Generated by Django 2.0 on 2018-04-23 09:19

from django.db import migrations


def load_json_content(apps, schema_editor):
    from django.core import management

    if 1:
        from subprocess import call
        res = call(['python', 'kdlencrypt.py', 'decrypt'])
        if res != 0:
            raise Exception(
                'Could not decrypt research data.'
                ' Run `./kdlencrypt init` for more info'
            )
    if 1:
        management.call_command(
            'loaddata',
            'research_data/private/all_strings_1.0.json',
            verbosity=0
        )
    if 1:
        VisualisationPage = apps.get_model("dral_wagtail", "VisualisationPage")
        page = VisualisationPage.objects.get(id=7)
        page.title = 'Distribution of Relative Omission'
        page.slug = 'distribution-relative-omission'
        page.visualisation_code = 'relative-omission-by-translation'
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0010_auto_20180422_1409'),
    ]

    operations = [
        migrations.RunPython(load_json_content),
    ]
