# Generated by Django 2.0 on 2018-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0011_spreadsheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='cell',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sentence',
            name='cell_line',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
