# Generated by Django 2.0 on 2018-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0012_auto_20180708_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='cell',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
