# Generated by Django 2.1.5 on 2019-02-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0013_auto_20180709_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='cell',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
