# Generated by Django 2.1.5 on 2019-02-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0014_auto_20190209_2222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurence',
            unique_together={('chapter', 'lemma', 'cell_col', 'language')},
        ),
    ]
