# Generated by Django 2.1.5 on 2019-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0015_auto_20190210_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='forms',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
