# Generated by Django 2.1.5 on 2019-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0016_lemma_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='string',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='lemma',
            unique_together={('string', 'forms')},
        ),
    ]
