# Generated by Django 2.1.5 on 2019-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0018_auto_20190210_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
