# Generated by Django 2.1.5 on 2019-03-26 17:21

from django.db import migrations
from django.utils.text import slugify


def set_language_slug(apps, schema_editor):

    for lg in apps.get_model('dral_text', 'language').objects.all():
        lg.slug = slugify(lg.name)
        lg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0021_auto_20190326_1720'),
    ]

    operations = [
        migrations.RunPython(set_language_slug),
    ]
