# Generated by Django 2.1.5 on 2019-03-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0022_set_language_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['index'], name='dral_text_s_index_cbcf1a_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['chapter'], name='dral_text_s_chapter_bf9df9_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['language'], name='dral_text_s_languag_13c74a_idx'),
        ),
    ]
