# Generated by Django 2.1.5 on 2019-06-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0026_auto_20190613_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
