# Generated by Django 2.1.5 on 2019-06-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0027_text_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='original_publication_date',
        ),
        migrations.RemoveField(
            model_name='text',
            name='production_date',
        ),
        migrations.AddField(
            model_name='text',
            name='original_publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='production_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
