# Generated by Django 2.2.3 on 2019-07-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0028_auto_20190628_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentences', to='dral_text.Text'),
        ),
    ]
