# Generated by Django 2.2.3 on 2019-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_text', '0029_auto_20190708_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='An internal code for this visualisation, please DO NOT edit', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Public name of this visualisation', max_length=30, unique=True)),
                ('type', models.CharField(choices=[('featured', 'Featured'), ('exploratory', 'Exploratory')], default='exploratory', help_text='Select "Featured" for more polished / final visualisation', max_length=30)),
                ('visibility', models.TextField(choices=[('dev', 'Development'), ('liv', 'Live')], default='dev', help_text='If "Live" the viz is publicly visible', max_length=30)),
                ('short_description', models.TextField(blank=True, help_text='Short description on top of the visualisation.\n        Ideally one sentence. You can insert links to keep things concise.\n        Formatting is done by using\n        <a href="https://daringfireball.net/projects/markdown/syntax">\n        markdown syntax</a>.')),
                ('display_order', models.IntegerField(default=0, help_text='visualisation with lower number appear first on the site')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
