# Generated by Django 2.0 on 2018-04-18 17:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('dral_wagtail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualisationSetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('short_title', models.CharField(blank=True, default=None, help_text='A very short label used to represent this page in a menu', max_length=32, null=True, verbose_name='Menu label')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
