# Generated by Django 2.0 on 2018-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dral_wagtail', '0003_auto_20180418_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationpage',
            name='visualisation_code',
            field=models.SlugField(blank=True, default=None, max_length=32, null=True, verbose_name='Visualisation Code'),
        ),
    ]
