# Generated by Django 2.1.5 on 2019-03-26 13:47

from django.db import migrations


def del_visualisationpages(apps, schema_editor):

    VisualisationPage = apps.get_model('dral_wagtail', 'visualisationpage')

    VisualisationPage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dral_wagtail', '0004_visualisationpage_visualisation_code'),
    ]

    operations = [
        migrations.RunPython(del_visualisationpages),
    ]
