# Generated by Django 2.1.5 on 2019-03-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('dral_wagtail', '0005_del_visualisationpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisationpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='VisualisationPage',
        ),
    ]
